name = "rian-example"

main = "worker.ts"
workers_dev = true

compatibility_date = "2023-03-07"
compatibility_flags = ['nodejs_compat']

kv_namespaces = [
	{ binding = "DATA", id = "<fillme>", preview_id = "<fillme>" }
]
